### ISSUE TITLE
Add react and react-dom 17 to peer-dependencies

### ISSUE THREAD

**Issue by leedavidcs** [HyvorTalk/hyvor-talk-react#2]
Can we add react and react-dom v17.0.0 to the list of peer-dependencies? We're running into this error with this package:
```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.0 || ^16.0.0" from hyvor-talk-react@1.0.3
```

**Comment by supunkavinda** [comment]
Added react 17 to peer dependencies and dropped react-dom dependency in version 2.0.0.

Thank you!
